### ISSUE TITLE
TypeError: dep.getResourceIdentifier is not a function

### ISSUE THREAD

**Issue by shakaran** [hakimel/Ladda#83]
I am getting this error on 1.0.0 building in production my app:
  
```
cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
 10% building modules 8/14 modules 6 active …eb/node_modules/ladda/dist/ladda.min.jsTypeError: dep.getResourceIdentifier is not a function
    at addDependency (/var/www/web/node_modules/webpack/lib/Compilation.js:394:30)
    at iterationOfArrayCallback (/var/www/web/node_modules/webpack/lib/Compilation.js:80:3)
    at addDependenciesBlock (/var/www/web/node_modules/webpack/lib/Compilation.js:414:5)
    at Compilation.processModuleDependencies (/var/www/web/node_modules/webpack/lib/Compilation.js:425:4)
    at afterBuild (/var/www/web/node_modules/webpack/lib/Compilation.js:552:16)
    at _this.buildModule.err (/var/www/web/node_modules/webpack/lib/Compilation.js:598:11)
    at callback (/var/www/web/node_modules/webpack/lib/Compilation.js:349:35)
    at module.build.error (/var/www/web/node_modules/webpack/lib/Compilation.js:385:12)
    at handleParseResult (/var/www/web/node_modules/webpack/lib/NormalModule.js:371:12)
    at doBuild.e (/var/www/web/node_modules/webpack/lib/NormalModule.js:393:6)
    at runLoaders (/var/www/web/node_modules/webpack/lib/NormalModule.js:272:12)
    at /var/www/web/node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/var/www/web/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at Array.<anonymous> (/var/www/web/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/var/www/web/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/var/www/web/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at /var/www/web/node_modules/webpack/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:447:3)

```

**Comment by shakaran** [comment]
Upgrading to 1.0.6, I get the same result too

**Comment by theodorejb** [comment]
I use Ladda with Webpack and haven't had any issues. How are you importing the module?
